CREATE TABLE BARCOS 
(
	MATRICULA VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	CLASE VARCHAR2(10),
	ARMADOR VARCHAR2(10),
	CAPACIDAD NUMBER(10),
	NACIONALIDAD VARCHAR2(10),
	CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA),
	CONSTRAINT CHK1_BARCOS CHECK (REGEXP_LIKE(MATRICULA,'^[A-Z]{2}[-][0-9]{4}$'))
);

INSERT INTO BARCOS VALUES ('AB-8976', 'LOLA', 'YATE', 'IBERIA', 100, 'ESPAÑA');
INSERT INTO BARCOS VALUES ('AH-5476', 'MARI', 'BARCO', 'COSTA SOL', 100, 'ESPAÑA');


CREATE TABLE ESPECIE
(
	CODIGO VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	TIPO VARCHAR2(10),
	CUPOPORBARCO NUMBER(20),
	CALADERO_PRINCIPAL VARCHAR2(10),
	CONSTRAINT PK_ESPECIE PRIMARY KEY (CODIGO)
);

INSERT INTO ESPECIE VALUES ('1234', 'COSTA', 'YATE', 100, '7776');
INSERT INTO ESPECIE VALUES ('5476', 'MARISOL', 'BARCO', 100, '7865');

CREATE TABLE CALADERO
(
	CODIGO VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	UBICACION VARCHAR2(10),
	ESPECIE_PRINCIPAL VARCHAR2(10),
	CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO),
	CONSTRAINT CHK1_CALADERO CHECK (UPPER(NOMBRE)=NOMBRE),
	CONSTRAINT CHK2_CALADERO CHECK (UPPER(UBICACION)=UBICACION)
);

ALTER TABLE ESPECIE ADD CONSTRAINT FK2_ESPECIES FOREIGN KEY(CALADERO_PRINCIPAL) REFERENCES CALADERO(CODIGO);
ALTER TABLE CALADERO ADD CONSTRAINT FK1_CALADERO FOREIGN KEY (ESPECIE_PRINCIPAL) REFERENCES ESPECIE(CODIGO);
ALTER TABLE CALADERO ADD NOMBRE_CIENTIFICO VARCHAR2(10);

INSERT INTO CALADERO VALUES ('7776', 'SANT', 'EIVISSA', 'YATE', '1234');
INSERT INTO CALADERO VALUES ('7865', 'DENIA', 'DENIA', 'BARCO','5476');

SELECT * FROM ESPECIE;


CREATE TABLE LOTES 
(
	CODIGO VARCHAR2(10),
	MATRICULA VARCHAR2(10),
	NUMKILOS NUMBER(50),
	PRECIOSPORKILOSALIDA NUMBER(5,2),
	PRECIOPORKILOADJUDICADO NUMBERB(5,2),
	FECHAVENTA DATE NOT NULL,
	COD_ESPECIE VARCHAR2(10),
	CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_LOTES FOREIGN KEY (MATRICULA) REFERENCES BARCOS (MATRICULA),
	CONSTRAINT FK2_LOTES FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE (CODIGO),
	CONSTRAINT CHK1_LOTES CHECK (PRECIOPORKILOADJUDICADO>PRECIOKILOSALIDA),
	CONSTRAINT CHK2_LOTES CHECK (PRECIPORKILOADJUDICADO>O),
	CONSTRAINT CHK2_LOTES CHECK (NUMKILO>O),
	CONSTRAINT CHK2_LOTES CHECK (PRECIOKILOSALIDA>O)
	
);

INSERT INTO LOTES VALUES ('8676', 'AB-8976', 10, 12.65, 100.76, TO_DATE('22/04/21','DD/MM/YY'), '1234' );
INSERT INTO LOTES VALUES ('0987', 'AH-5476', 10, 1234.76, 189.98, TO_DATE('25/04/21','DD/MM/YY'), '5476');

CREATE TABLE FECHAS_CAPTURAS_PERMITIDAS
(
	COD_ESPECIES VARCHAR2(10),
	COD_CALADERO VARCHAR2(10),
	FECHA_INICIAL DATE,
	FECHA_FINAL DATE,
	CONSTRAINT PK_FECHAS PRIMARY KEY (COD_ESPECIES, COD_CALADERO),
	CONSTRAINT FK1_FECHAS FOREIGN KEY (COD_ESPECIES) REFERENCES ESPECIES(CODIGO),
	CONSTRAINT FK1_FECHAS FOREIGN KEY (COD_CALADERO) REFERENCES CALADERO(CODIGO)
);

INSERT INTO FECHAS_CAPTURAS_PERMITIDAS VALUES ('1234', '7776', TO-DATE('22/08/20','DD-MM-YY'), TO_DATE('22/12/21','DD/MM/YY'));
INSERT INTO FECHAS_CAPTURAS_PERMITIDAS VALUES ('5476', '7865', TO-DATE('22/09/21','DD-MM-YY'), TO_DATE('22/03/19','DD/MM/YY'));

ALTER TABLE BARCOS DROP ARMADOR;







