--alter session set "_oracle_script"=true;  
--create USER SANCHEZCRISTINA identified by SANCHEZCRISTINA;
--GRANT CONNECT, RESOURCE, DBA TO SANCHEZCRISTINA;

CREATE TABLE MEDICO 
(
	COD_MEDICO NUMBER(10),
	NOMBRE VARCHAR2(20),
	ESPECIALIDAD VARCHAR2(50) DEFAULT 'FAM',
	COD_DIRECTOR NUMBER(10),
	CONSTRAINT PK_MED PRIMARY KEY (COD_MEDICO),
	CONSTRAINT FK_MED FOREIGN KEY (COD_DIRECTOR) REFERENCES MEDICO(COD_MEDICO) ON DELETE SET NULL
);

CREATE TABLE ENFERMO
(
	COD_INSCRIPCION NUMBER(10),
	NSS VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	SEXO VARCHAR2(1),
	CONSTRAINT PK_ENF PRIMARY KEY (COD_INSCRIPCION)
);

CREATE TABLE HABITACION
(
	NUM_HABITACION NUMBER(10),
	NUMERO_CAMAS NUMBER(10),
	CONSTRAINT PK_HAB PRIMARY KEY (NUM_HABITACION),
	CONSTRAINT CH1_HAB CHECK (NUM_HABITACION>=100 AND NUM_HABITACION<=399),
	CONSTRAINT CH2_HAB CHECK (NUMERO_CAMAS<=3)
);

CREATE TABLE INGRESO
(
	COD_INGRESO NUMBER (10),
	COD_INSCRIPCION NUMBER(10),
	FECHA_INGRESO DATE DEFAULT SYSDATE,
	FECHA_ALTA DATE,
	NUM_HABITACION NUMBER(10),
	CONSTRAINT PK_INGR PRIMARY KEY (COD_INGRESO),
	CONSTRAINT FK1_INGR FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION) ON DELETE CASCADE,
	CONSTRAINT FK2_INGR FOREIGN KEY (NUM_HABITACION) REFERENCES HABITACION (NUM_HABITACION),
	CONSTRAINT CH1_INGR CHECK (FECHA_ALTA>FECHA_INGRESO) 
);

CREATE TABLE VISITAS
(
	COD_MEDICO NUMBER(10),
	COD_INSCRIPCION NUMBER(10),
	FECHA DATE,
	DIAGNOSTICO VARCHAR2(10),
	CONSTRAINT PK_VI PRIMARY KEY (COD_MEDICO, COD_INSCRIPCION),
	CONSTRAINT FK1_VI FOREIGN KEY (COD_MEDICO) REFERENCES MEDICO(COD_MEDICO) ON DELETE CASCADE,
	CONSTRAINT FK2_VI FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION) ON DELETE CASCADE
);

TRUNCATE TABLE HABITACION;

