CREATE TABLE EQUIPOS
(
	COD_EQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	LOCALIDAD VARCHAR2(15),
	CONSTRAINT PK_EQUIPOS PRIMARY KEY (COD_EQUIPO)
);

ALTER TABLE EQUIPOS ADD CONSTRAINT CHK1_EQUIPO CHECK (regexp_like(COD_EQUIPO,'^[0-9]{1}'));
ALTER TABLE EQUIPOS ADD GOLES_MARCADOS NUMBER(3);

CREATE TABLE JUGADORES
(
	COD_JUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHA_NACIMINETO DATE,
	DEMARCACION VARCHAR2(10),
	COD_EQUIPO VARCHAR(4),
	CONSTRAINT PK_JUGADORES PRIMARY KEY (COD_JUGADOR),
	CONSTRAINT FK_JUGADORES FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPOS(COD_EQUIPO)
);

ALTER TABLE JUGADORES ADD CONSTRAINT CHK1_JUGADORES CHECK (regexp_like(NOMBRE,'^[A-Z]{1}[a-z]{29}$'));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK2_JUGADORES CHECK (DEMARCACION IN ('PORTERO','DEFENSA','MEDIO','DELANTERO'));

CREATE TABLE PARTIDOS 
(
	COD_PARTIDO VARCHAR2(4),
	COD_EQUIPO_LOCAL VARCHAR2(4),
	COD_EQUIPO_VISITANTE VARCHAR2(4),
	FECHA DATE,
	COMPETICION VARCHAR2(4),
	JORNADA VARCHAR2(20),
	CONSTRAINT PK_PARTIDOS PRIMARY KEY (COD_PARTIDO),
	CONSTRAINT FK_PARTIDOS FOREIGN KEY (COD_EQUIPO_LOCAL) REFERENCES EQUIPOS(COD_EQUIPO), 
	CONSTRAINT FK2_PARTIDOS FOREIGN KEY (COD_EQUIPO_VISITANTE) REFERENCES EQUIPOS(COD_EQUIPO)
);

ALTER TABLE PARTIDOS ADD CONSTRAINT CHK_PARTIDOS CHECK (((EXTRACT(MONTH FROM FECHA)))<>7 OR (EXTRACT(MONTH FROM FECHA))<>8);
ALTER TABLE PARTIDOS ADD CONSTRAINT CHK2_PARTIDOS CHECK (COMPETICION IN('COPA', 'LIGA'));

CREATE TABLE INCIDENCIAS 
(
	NUM_INDICENCIAS VARCHAR2(6),
	COD_PARTIDO VARCHAR2(4),
	COD_JUGADOR VARCHAR2(4),
	MINUTO NUMBER(2),
	TIPO VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INDICENCIAS),
	CONSTRAINT FK_INCIDENCIAS FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS(COD_PARTIDO),
	CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES(COD_JUGADOR)
);

ALTER TABLE INCIDENCIAS ADD CONSTRAINT CHK_INCIDENCIAS CHECK (MINUTO BETWEEN 1 AND 100);




