--alter session set "_oracle_script"=true;  
--create USER EXAMENREPASO identified by EXAMENREPASO;
--GRANT CONNECT, RESOURCE, DBA TO EXAMENREPASO;

CREATE TABLE FAMILIA 
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	CONSTRAINT PK_FA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO 
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	NOMBRE_FAMILIA VARCHAR2(20),
	CONSTRAINT PK_GE PRIMARY KEY (NOMBRE),
	CONSTRAINT FK_GE FOREIGN KEY (NOMBRE_FAMILIA) REFERENCES FAMILIA(NOMBRE)
);

CREATE TABLE ESPECIE 
(
	NOMBRE VARCHAR2(20),
	CARACTERISTICAS VARCHAR2(50),
	NOMBRE_GENERO VARCHAR2(20),
	CONSTRAINT PK_ES PRIMARY KEY (NOMBRE),
	CONSTRAINT FK_ES FOREIGN KEY (NOMBRE_GENERO) REFERENCES GENERO(NOMBRE)
);

CREATE TABLE ZONA 
(
	NOMBRE VARCHAR2(20),
	LOCALIDAD VARCHAR2(20),
	EXTENSION NUMBER(10),
	PROTEGIDA VARCHAR2(10),
	CONSTRAINT PK_ZO PRIMARY KEY (NOMBRE),
	CONSTRAINT CH_ZO CHECK (PROTEGIDA IN ('SI', 'NO'))

);

CREATE TABLE PERSONA 
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	DIRECCION VARCHAR2(50),
	TELEFONO VARCHAR2(9),
	USUARIO VARCHAR2(20),
	CONSTRAINT PK_PER PRIMARY KEY (DNI)
);

CREATE TABLE COLECCION 
(
	PRECIO NUMBER(5,2),
	FECHA_INICIO DATE,
	Nº_EJEMPLARES NUMBER(10),
	DNI_PERSONA VARCHAR2(9),
	CONSTRAINT PK_COLE PRIMARY KEY (DNI_PERSONA),
	CONSTRAINT FK_COLE FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA(DNI),
	CONSTRAINT CH_COLE CHECK (Nº_EJEMPLARES BETWEEN 1 AND 150)
	
);

CREATE TABLE EJEMPLAR_MARIPOSA
(
	HORA_CAPTURA VARCHAR2(10),
	FECHA_CAPTURA DATE,
	NOMBRE_COMUN VARCHAR2(20),
	PRECIO_EJEMPLAR NUMBER(5,2),
	NOMBRE_ESPECIE VARCHAR2(20),
	NOMBRE_ZONA VARCHAR2(20),
	DNI_PERSONA VARCHAR2(9),
	DNI_PERSONA_COLECCION VARCHAR2(9),
	FECHA_COLECCION DATE,
	CONSTRAINT PK_EJ PRIMARY KEY (HORA_CAPTURA, FECHA_CAPTURA, NOMBRE_ESPECIE, NOMBRE_ZONA, DNI_PERSONA),
	CONSTRAINT FK_EJ FOREIGN KEY (NOMBRE_ESPECIE) REFERENCES ESPECIE (NOMBRE),
	CONSTRAINT FK_EJ2 FOREIGN KEY (NOMBRE_ZONA) REFERENCES ZONA (NOMBRE),
	CONSTRAINT FK_EJ3 FOREIGN KEY (DNI_PERSONA) REFERENCES PERSONA (DNI),
	CONSTRAINT FK_EJ4 FOREIGN KEY (DNI_PERSONA_COLECCION) REFERENCES COLECCION (DNI_PERSONA),
	CONSTRAINT CH_EJ CHECK (PRECIO_EJEMPLAR>0)
);


ALTER TABLE PERSONA ADD APELLIDOS VARCHAR2(20);
ALTER TABLE ZONA ADD CONSTRAINT CH2_ZO CHECK (EXTENSION BETWEEN 100 AND 1500);
ALTER TABLE EJEMPLAR_MARIPOSA DROP CONSTRAINT CH_EJ;
ALTER TABLE EJEMPLAR_MARIPOSA MODIFY FECHA_CAPTURA DATE DEFAULT SYSDATE;







