
--1
ALTER TABLE ENFERMO ADD CONSTRAINT CH_ENF CHECK (SEXO IN ('H', 'M'));

-- 2
-- ESTO OCURRE DEBIDO A QUE EL COD_MEDICO Y EL COD_INCRIPCION SON LAS PRIMARY KEYS DE VISITAS POR LO QUE SI UN MEDICO
-- VISITA DOS VECES A UN MISMO PACIENTE COMO SE MUESTRA ABAJO LAS CLAVES PRIMARIAS VAN A ESTAR REPETIDAS Y ESO NO SE PUEDE
-- INSERT INTO VISITAS (COD_MEDICO, COD_INSCRIPCION, FECHA, DIAGNOSTICO) VALUES (1, 1, SYSDATE, 'MIOPIA');
-- INSERT INTO VISITAS (COD_MEDICO, COD_INSCRIPCION, FECHA, DIAGNOSTICO) VALUES (1, 1, SYSDATE, 'MIOPIA');
-- LA FORMA DE ARREGLARLO ES CAMBIAR LA PRIMARY KEY DE VISITAS POR UNA DIFERENTE PARA QUE LOS OTROS DATOS SE PUEDAN REPETIR
ALTER TABLE VISITAS ADD COD_VISITAS NUMBER(10);
ALTER TABLE VISITAS DROP CONSTRAINT PK_VI;
ALTER TABLE VISITAS ADD CONSTRAINT PK_VI PRIMARY KEY (COD_VISITAS);

--3
ALTER TABLE ENFERMO MODIFY NSS VARCHAR2(12); 

--4
INSERT INTO MEDICO (COD_MEDICO, NOMBRE, ESPECIALIDAD, COD_DIRECTOR) VALUES (1, 'BENITO', 'OCULISTA', 1);
INSERT INTO ENFERMO (COD_INSCRIPCION, NSS, NOMBRE, SEXO) VALUES (1, '123456789101', 'JUAN', 'H');
INSERT INTO ENFERMO (COD_INSCRIPCION, NSS, NOMBRE, SEXO) VALUES (2, '746583748273', 'MARIA', 'M');

--5
INSERT INTO HABITACION (NUM_HABITACION, NUMERO_CAMAS) VALUES (102, 2);
INSERT INTO INGRESO (COD_INGRESO, COD_INSCRIPCION, FECHA_INGRESO, NUM_HABITACION) VALUES (1, 1, SYSDATE, 102 );

--6
INSERT INTO VISITAS (COD_MEDICO, COD_INSCRIPCION, FECHA, DIAGNOSTICO) VALUES (1, 1, 1, SYSDATE, 'MIOPIA');

--7
ALTER TABLE VISITAS ADD FECHA_PROXIMA_VISITA DATE;

--8 
UPDATE ENFERMO SET NOMBRE = 'JONH NIEVE' WHERE COD_INSCRIPCION =1;

--9
DELETE FROM ENFERMO WHERE COD_INSCRIPCION=1;

--10
--DROP TABLE MEDICO CASCADE CONSTRAINT;
--DROP TABLE ENFERMO CASCADE CONSTRAINT;
--DROP TABLE INGRESO CASCADE CONSTRAINT;
--DROP TABLE VISITAS CASCADE CONSTRAINT;
--DROP TABLE HABITACION CASCADE CONSTRAINT;



-- APARTADO 3

-- 1
-- LOS DATOS CREADOS NO PERSISTIRAR EN LA BASE DE DATOS PORQUE TIENES EL AUTOCOMMIT DESACTIVADO Y NO HAS HECHO COMMIT U O NO HAS REALIZADO 
-- UNA OPERACION DE DDL POR LO TANTO ESOS DATOS NO LOS LLEGA A VER OTRO PROGRAMADOR 


-- 2
-- SI , LOS DATOS PERSISTIRAN YA QUE DESPUES DE METER ESOS DATOS REALIZASTE UNA OPERACION DDL COMO LA DE CREAR TABAL QUE TIENEN POR DEFECTO 
-- UN AUTOCOMMIT INCLUIDO, POR LO QUE OTRO PRORAMADOR YA PODRA VER ESOS DATOS

-- 3
-- NO SERIA POSIBLE VOLVER A ESOS DATOS YA QUE CREASTE UNA TABLA POSTERIORMENTE QUE TIENE EL AUTOCOMMIT POR DEFECTO ASI QUE ESOS DATOS YA SE GUARDARON 
-- EN EL SISTEMA, EL UNICO CASO PARA MODIFICARLOS SERIA ACTUALIZARLOS CON UN UPDATE, PERO NO PUEDES RETROCEDER

-- 4
-- PARA QUE LOS DATOS PERSISTAN, YA QUE TINES EL AUTOCOMMIT DESACTIVADO, DEBES REALIZAR LA OPERACION "COMMIT;" AL FINAL DE INSERTAR LOS DATOS
-- O REALIZAR UNA OPERACION DDL COMO LA CREACION DE TABLAS QUE TIENE UN AUTOCOMMIT POR DEFECTO

-- 5
-- YA PERSISTISTE LOS DATOS DE LA TABLA CLIENTE EN LA BASE DE DATOS CON UN COMMIT, ASI QUE LAS OPERACIONES HECHAS POSTERIORMENTE  DE ESE COMMIT SE PUEDEN ELIMINAR
-- CON UN ROLLBACK, RECUPERANDO LOS DATOS PERDIDOS (SIEMPRE Y CUENDO NO HAGAS UN COMMIT LUEGO DE BORRAR ESOS DATOS)

-- 6
-- EL SAVEPOINT COMO SU NOMBRE INDICA SON PUNTOS DE GUADADOS QUE PODEMOS INSERTAR A LO LARGO DEL SCRIP CON EL COMANDO "SAVEPOINT PRIMERO;" POR EJEMPLO,
-- CON ESTOS PUNTOS DE GUARDADOS PODREMOS RETROCEDER EN EL SCRIP CON EL COMANDO "ROLLBACK TO ;" POR EJEMPLO TENEMOS LOS SIGUIENTES DATOS:
--INSERT INTO MEDICO (COD_MEDICO, NOMBRE, ESPECIALIDAD, COD_DIRECTOR) VALUES (1, 'BENITO', 'OCULISTA', 1);
--INSERT INTO ENFERMO (COD_INSCRIPCION, NSS, NOMBRE, SEXO) VALUES (1, '123456789101', 'JUAN', 'H');
--INSERT INTO ENFERMO (COD_INSCRIPCION, NSS, NOMBRE, SEXO) VALUES (2, '746583748273', 'MARIA', 'M');
-- SAVEPOINT PRIMERO;
--INSERT INTO HABITACION (NUM_HABITACION, NUMERO_CAMAS) VALUES (102, 2);
--INSERT INTO INGRESO (COD_INGRESO, COD_INCRIPCION, FECHA_INGRESO, NUM_HABITACION) VALUES (1, 1, SYSDATE, 102 );
-- SAVEPOINT SEGUNDO;
--INSERT INTO VISITAS (COD_MEDICO, COD_INCRIPCION, FECHA, DIAGNOSTICO) VALUES (1, 1, SYSDATE, 'TIENE MIOPIA');
-- SAVEPOINT TERCERO;
--UPDATE ENFERMO SET NOMBRE LIKE 'JONH NIEVE' WHERE COD_INSCRIPCION =1;
-- UNA VEZ INSERTADO ESTOS DATOS NOS DAMOS CUENTA QUE LOS DATOS A PARTIR DEL SEGUNDO SAVEPOINT NO NOS HACEN FALTA POS PODEMOS RETROCEDER CON EL 
-- ROLLBACK TO SEGUNDO;, Y LOS DATOS POSTERIORES SE ELIMINARAN INCLUYENDO EL SAVEPOINT TERCERO POR LO QUE YA NO PODREMOS ACCEDER A ESE, SOLO
-- AL SAVEPOINT PRIMERO SI NOS HE NECESARIO



