CREATE TABLE DEPARTAMENTOS
(
	CODIGO NUMBER(10),
	DESCRIPCION VARCHAR2(100),
	CONSTRAINT PK_DEP PRIMARY KEY (CODIGO)
	
);

CREATE SEQUENCE SQ_DEP
START WITH 1
INCREMENT BY 1;
SELECT SQ_DEP.CURRAL FROM DUAL;

INSERT INTO DEPARTAMENTOS VALUES (SQ_DEP.NEXTVAL, 'COMERCIO');
INSERT INTO DEPARTAMENTOS VALUES (SQ_DEP.NEXTVAL, 'PUBLICIDAD');
INSERT INTO DEPARTAMENTOS VALUES (SQ_DEP.NEXTVAL, 'MANTENIMIENTO');
INSERT INTO DEPARTAMENTOS VALUES (SQ_DEP.NEXTVAL, 'LIMPIEZA');
