CREATE TABLE FABRICANTES
(
	COD_FABRICANTES NUMBER (10),
	NOMBRE VARCHAR2(15),
	PAIS VARCHAR2(15),
	CONSTRAINT PK_FABRICANTES PRIMARY KEY (COD_FABRICANTES),
	CONSTRAINT CH1_FAB CHECK (UPPER(NOMBRE)=NOMBRE),
	CONSTRAINT CH2_FAB CHECK (UPPER(PAIS)=PAIS),
	CONSTRAINT CH3_FAB CHECK (COD_FABRICANTES<3)

);

CREATE TABLE ARTICULOS
(
	ARTICULO VARCHAR2(20),
	COD_FABRICANTES NUMBER(10),
	PESO NUMBER(10) NOT NULL,
	CATEGORIA VARCHAR2(10) NOT NULL,
	PRECIO_VENTA NUMBER(4,2),
	PRECIO_COSTO NUMBER(4,2),
	EXISTENCIAS NUMBER(10),
	CONSTRAINT PK_ART PRIMARY KEY (ARTICULO, COD_FABRICANTES, PESO, CATEGORIA),
	CONSTRAINT FK_ART FOREIGN KEY (COD_FABRICANTES) REFERENCES FABRICANTES(COD_FABRICANTES),
	CONSTRAINT CH1_ART CHECK (PRECIO_VENTA>0),
	CONSTRAINT CH2_ART CHECK (PRECIO_COSTO>0),
	CONSTRAINT CH3_ART CHECK (COD_FABRICANTES<3),
	CONSTRAINT CH4_ART CHECK (PESO<3),
	CONSTRAINT CH5_ART CHECK (EXISTENCIAS<5),
	CONSTRAINT CH6_ART CHECK (CATEGORIA IN ('PRIMERA','SEGUNDA','TERCERA')),
	CONSTRAINT CH7_ART CHECK (UPPER(CATEGORIA)=CATEGORIA)
	
);

CREATE TABLE TIENDAS
(
	NIF VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(20),
	POBLACION VARCHAR2(20),
	PROVINCIA VARCHAR2(20),
	CODPOSTAL NUMBER (10),
	CONSTRAINT PK_TI PRIMARY KEY (NIF),
	CONSTRAINT CH1_TIEN CHECK (CODPOSTAL<=5),
	CONSTRAINT CH2_TIEN CHECK (UPPER(PROVINCIA)=PROVINCIA)
);

CREATE TABLE PEDIDOS
(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTES NUMBER(10),
	PESO NUMBER(10),
	CATEGORIA VARCHAR2(10),
	FECHA_PEDIDO DATE NOT NULL,
	UNIDADES_PEDIDAS NUMBER(10),
	CONSTRAINT PK_PEDI PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTES, PESO, CATEGORIA, FECHA_PEDIDO),
	CONSTRAINT FK1_PEDI FOREIGN KEY (COD_FABRICANTES) REFERENCES FABRICANTES(COD_FABRICANTES),
	CONSTRAINT FK2_PEDI FOREIGN KEY (ARTICULO, COD_FABRICANTES, PESO, CATEGORIA) REFERENCES ARTICULOS (ARTICULO, COD_FABRICANTES, PESO, CATEGORIA) ON DELETE CASCADE,
	CONSTRAINT FK3_PEDI FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
	CONSTRAINT CH1_PEDI CHECK (UNIDADES_PEDIDAS>0),
	CONSTRAINT CH2_PEDI CHECK (COD_FABRICANTES<=3),
	CONSTRAINT CH3_PEDI CHECK (PESO<=3),
	CONSTRAINT CH4_PEDI CHECK (UNIDADES_PEDIDAS<=4)	
);

CREATE TABLE VENTAS 
(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTES NUMBER(10),
	PESO NUMBER(10),
	CATEGORIA VARCHAR2(10),
	FECHA_VENTA DATE DEFAULT SYSDATE NOT NULL,
	UNIDADES_VENDIDAS NUMBER(10),
	CONSTRAINT PK_VENT PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTES, PESO, CATEGORIA, FECHA_VENTA),
	CONSTRAINT FK1_VENT FOREIGN KEY (COD_FABRICANTES) REFERENCES FABRICANTES(COD_FABRICANTES),
	CONSTRAINT FK2_VENT FOREIGN KEY (ARTICULO, COD_FABRICANTES, PESO, CATEGORIA) REFERENCES ARTICULOS (ARTICULO, COD_FABRICANTES, PESO, CATEGORIA) ON DELETE CASCADE,
	CONSTRAINT FK3_VENT FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
	CONSTRAINT CH1_VENT CHECK (UNIDADES_VENDIDAS>0),
	CONSTRAINT CH2_VENT CHECK (COD_FABRICANTES<=3),
	CONSTRAINT CH3_VENT CHECK (PESO<=3),
	CONSTRAINT CH4_VENT CHECK (UNIDADES_VENDIDAS<=4)	
);

ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);
ALTER TABLE PEDIDOS ADD PVP_PEDIDOS VARCHAR2(50);
ALTER TABLE VENTAS ADD PVP_VENDIDAS VARCHAR2(50);
ALTER TABLE FABRICANTES DROP COLUMN PAIS;
ALTER TABLE VENTAS DROP CONSTRAINT CH1_VENT;
ALTER TABLE VENTAS ADD CONSTRAINT CH5_VENT CHECK (UNIDADES_VENDIDAS>100);
ALTER TABLE VENTAS DROP CONSTRAINT CH5_VENT;

--DROP TABLE VENTAS CASCADE CONSTRAINT;
--DROP TABLE PEDIDOS;
--DROP TABLE TIENDAS;
--DROP TABLE ARTICULOS;
--DROP TABLE FABRICANTE;
























