/* Ejercicio 1*/

INSERT INTO PERSONA VALUES ('12345678A' , 'CRISTINA', 'SANCHEZ', 'SEVILLA', 'JUAN RAMON', 10, '123454321', TO_DATE('10/06/2004', 'DD/MM/YYYY'), 0);
INSERT INTO ALUMNO VALUES ( '1234' , '12345678A');
INSERT INTO ALUMNO_ASIGNATURA VALUES ('1234 ', '160002' , 1);

/*Ejercicio 2*/

INSERT INTO PERSONA  VALUES ('77222122K', 'MARTA', 'LOPEZ', 'SEVILLA', 'TARIFA', 9, '615891432', TO_DATE('22/07/1981', 'DD/MM/YYYY'), 0);
INSERT INTO PROFESOR VALUES ('P121', '77222122K');
UPDATE ASIGNATURA SET IDPROFESOR = 'P121' WHERE NOMBRE = 'Contabilidad';
DELETE FROM PROFESOR WHERE IDPROFESOR = 'P117';


/*Ejercicio 3*/

CREATE TABLE ALUMNOS_MUYREPETIDORES
(
	IDASIGNATURA VARCHAR2(20),
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	APELLIDO VARCHAR2(10),
	TELEFONO VARCHAR2(9),
	FECHA_NACIMIENTO DATE,
	CONSTRAINT PK_AMR PRIMARY KEY (IDASIGNATURA, DNI)
);

/*Ejercicio 4*/

ALTER TABLE ALUMNOS_MUYREPETIDORES ADD OBSERVACIONES VARCHAR2(50);
UPDATE ALUMNOS_MUYREPETIDORES SET OBSERVACIONES = 'SE ENCUENTRA EN SEGUIMIENTO' WHERE TELEFONO LIKE '%20%';


/*Ejercicio 5*/

DELETE FROM ALUMNOS_MUYREPETIDORES WHERE TO_CHAR(FECHA_NACIMIENTO, 'MM/YYYY')='11/1971';

/*Ejercicio 6*/

CREATE TABLE RESUMEN_TITULACIONES 
(
	NOMBRE_TITULACION VARCHAR2(10),
	NUMEROASIGNATURAS VARCHAR2(6),
	CONSTRAINT PK_RT PRIMARY KEY (NOMBRE_TITULACION),
	CONSTRAINT FK1_RT FOREIGN KEY (NOMBRE_TITULACION) REFERENCES TITULACION (IDTITULACION),
	CONSTRAINT FK2_RT FOREIGN KEY (NUMEROASIGNATURAS) REFERENCES ASIGNATURA (IDASIGNATURA)
);

INSERT INTO RESUMEN_TITULACIONES (SELECT T.NOMBRE , COUNT(A.IDASIGNATURA)
FROM TITULACION t , ASIGNATURA a
WHERE T.IDTITULACION =A.IDTITULACION 
GROUP BY T.NOMBRE ;)

/*Ejercicio 7*/

CREATE TABLE JUEGODETRONOS
(
	COD_PERSONAJE NUMBER(10),
	NOMBRE VARCHAR2(10),
	EDAD NUMBER (10),
	CONSTRAINT PK_J PRIMARY KEY (COD_PERSONAJE)
);

CREATE SEQUENCE SQ_JU
START WITH 1
INCREMENT BY 1;
--SELECT SQ_JU.NEXTVAL FROM DUAL;

INSERT INTO JUEGODETRONOS VALUES (SQ_JU.NEXTVAL, 'JONH', 30);
INSERT INTO JUEGODETRONOS VALUES (SQ_JU.NEXTVAL, 'CLARY', 20);
INSERT INTO JUEGODETRONOS VALUES (SQ_JU.NEXTVAL, 'TROLL', 90);


/*Ejercicio 8*/

DELETE FROM JUEGODETRONOS WHERE (EDAD<18 AND NOMBRE LIKE 'A%');

/*Ejercicio 9*/

UPDATE PERSONAS SET TO_CHAR(FECHA_NACIMIENTO, 'DD/MM/YYYY')='22/07/1981' WHERE TO_CHAR(FECHA_NACIMIENTO, 'YYYY')>'2000';

/* Ejercicio 10*/

UPDATE PERSONAS SET (UPPER(NOMBRE)=NOMBRE); 



