CREATE TABLE DEPARTAMENTO
(
	CODIGO INT(10) auto_increment,
	NOMBRE VARCHAR(100) NOT NULL,
	PRESUPUESTO DOUBLE NOT NULL,
	CONSTRAINT PK_DEP PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO 
(
	CODIGO INT(10) AUTO_INCREMENT,
	NIF VARCHAR(9) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO1 VARCHAR(100) NOT NULL,
	APELLIDO2 VARCHAR(100),
	CODIGO_DEPARTAMENTO INT(10),
	CONSTRAINT PK_EMPL PRIMARY KEY (CODIGO),
	CONSTRAINT FK_EMPL FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

INSERT INTO DEPARTAMENTO VALUES (1, 'Desarrollo', 120000);
INSERT INTO DEPARTAMENTO VALUES (2, 'Sistemas', 150000);
INSERT INTO DEPARTAMENTO VALUES (3, 'Recursos Humanos', 280000);
INSERT INTO DEPARTAMENTO VALUES (4, 'Contabilidad', 110000);
INSERT INTO DEPARTAMENTO VALUES (5, 'I+D', 375000);
INSERT INTO DEPARTAMENTO VALUES (6, 'Proyectos', 0);
INSERT INTO DEPARTAMENTO VALUES (7, 'Publicidad', 0);

INSERT INTO EMPLEADO VALUES (1, '32481596F', 'Aarón', 'Rivero', 'Gómez', 1);
INSERT INTO EMPLEADO VALUES (2, 'Y5575632D', 'Adela', 'Salas', 'Díaz', 2);
INSERT INTO EMPLEADO VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);
INSERT INTO EMPLEADO VALUES (4, '77705545E', 'Adrián', 'Suárez', NULL, 4);
INSERT INTO EMPLEADO VALUES (5, '17087203C', 'Marcos', 'Loyola', 'Méndez', 5);
INSERT INTO EMPLEADO VALUES (6, '38382980M', 'María', 'Santana', 'Moreno', 1);
INSERT INTO EMPLEADO VALUES (7, '80576669X', 'Pilar', 'Ruiz', NULL, 2);
INSERT INTO EMPLEADO VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);
INSERT INTO EMPLEADO VALUES (9, '56399183D', 'Juan', 'Gómez', 'López', 2);
INSERT INTO EMPLEADO VALUES (10, '46384486H', 'Diego','Flores', 'Salas', 5);
INSERT INTO EMPLEADO VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', 1);
INSERT INTO EMPLEADO VALUES (12, '41234836R', 'Irene','Salas', 'Flores', NULL);
INSERT INTO EMPLEADO VALUES (13, '82635162B', 'Juan Antonio','Sáez', 'Guerrero', NULL);

INSERT INTO DEPARTAMENTO VALUES (8, 'MARKETING',1000);
INSERT INTO DEPARTAMENTO (NOMBRE, PRESUPUESTO) VALUES ('MANTENIMIENTO',10500);
#NO SE PUEDE PORQUE NO TIENE PRIMARY KEY
ALTER TABLE DEPARTAMENTO ADD GASTOS DOUBLE;
INSERT INTO DEPARTAMENTO VALUES (9, 'LIMPIEZA',1000, 500);
INSERT INTO EMPLEADO VALUES (14, '67384567A', 'Marcos','Garcia', 'Gil', 8);
INSERT INTO EMPLEADO VALUES ('67384567H', 'Maria','Gil', 'Acosta', 9);
#NO SE PUEDE PORQUE NO TIENE PRIMARY KEY

CREATE TABLE DEPARTAMENTO_BACKUP
(
	CODIGO INT(10),
	NOMBRE VARCHAR(100) NOT NULL,
	PRESUPUESTO DOUBLE NOT NULL,
	CONSTRAINT PK_DEPBK PRIMARY KEY (CODIGO)
);


INSERT INTO DEPARTAMENTO_BACKUP VALUES (1, 'Desarrollo', 120000);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (2, 'Sistemas', 150000);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (3, 'Recursos Humanos', 280000);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (4, 'Contabilidad', 110000);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (5, 'I+D', 375000);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (6, 'Proyectos', 0);
INSERT INTO DEPARTAMENTO_BACKUP VALUES (7, 'Publicidad', 0);

DELETE FROM DEPARTAMENTO WHERE NOMBRE='Proyectos';
#SI ES POSIBLE PORQUE NINGUN EMPLEADO DEPENDE DE ÉL
DELETE FROM DEPARTAMENTOS WHERE NOMBRE='Desarrollo';
#NO SE PUEDE PORQUE HAY EMPLEADOS QUE DEPENDE DE ÉL, PRIMERO DEBERIAMOS BORRAR A LOS EMPLEADOS
UPDATE DEPARTAMENTO SET CODIGO=30 WHERE NOMBRE='Recursos humanos';
#NO SE PUEDE PORQUE HAY EMPLEADOS QUE DEPENDE DE ÉL, PRIMERO DEBERIAMOS BORRAR A LOS EMPLEADOS
UPDATE DEPARTAMENTO SET CODIGO=40 WHERE NOMBRE='Publicidad';
#SI ES POSIBLE PORQUE NINGUN EMPLEADO DEPENDE DE ÉL
UPDATE DEPARTAMENTO SET PRESUPUESTO=PRESUPUESTO+50000 WHERE PRESUPUESTO<20000;
DELETE FROM EMPLEADO WHERE CODIGO_DEPARTAMENTO=NULL;





















